name: "crates-release"
description: "Increment crate version and release on crates.io"
inputs:
  version:
    description: "version to release under. can be major/minor/patch or semver. defaults to patch"
    required: true
    default: "patch"
  crates_token:
    description: "crates.io token for publishing"
    required: true

outputs:
  new-version:
    description: "New version released under"
    value: ${{ env.NEW_CRATE_VERSION }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-cargo
    - name: Install cargo edit
      run: cargo install cargo-edit
      shell: bash
    - name: Set version semver
      if: ${{ contains(github.event.inputs.version, '.') }}
      run: echo "NEW_CRATE_VERSION=$( cargo set-version ${{ github.event.inputs.version }} | awk '{print $NF}'  )" >> $GITHUB_ENV
      shell: bash
    - name: Set version bump
      if: ${{ !contains(github.event.inputs.version, '.') }}
      run: echo "NEW_CRATE_VERSION=$( cargo set-version --bump ${{ github.event.inputs.version }} | awk '{print $NF}' )" >> $GITHUB_ENV
      shell: bash
    - name: Publish on crates.io
      run: cargo publish --allow-dirty
      env:
        CARGO_REGISTRY_TOKEN: ${{ github.event.inputs.crates_token }}
      shell: bash
