name: crates-release
description: Increment crate version and release on crates.io
author: kaleidawave

branding:
  icon: arrow-up-circle
  color: red

inputs:
  version:
    description: A version argument, Can be major/minor/patch or semver. For monorepos a comma-sererated map of crate name to release argument
    required: true

  crates-token:
    description: crates.io token for publishing
    required: true

  publish-crates:
    description: whether to publish to crates.io
    default: "true"

  # TODO library
  working-directory:
    description: folder to run publish under
    default: "."

outputs:
  new-version:
    description: A single new version, "none" if multiple crates are updated
    value: ${{ steps.updater.outputs.new-version }}

  new-versions:
    description: A JSON array of crates and their new versions
    value: ${{ steps.updater.outputs.new-versions }}

  new-versions-description:
    description: A outline of what was updated to what versions
    value: ${{ steps.updater.outputs.new-versions-description }}

  new-versions-json-object:
    description: JSON object where keys are crates and values are the new version semver string
    value: ${{ steps.updater.outputs.new-versions-json-object }}

runs:
  using: "composite"
  steps:
  - id: is-repo-initilized
    run: echo "remote-url=$( git config --get remote.origin.url )" >> $GITHUB_OUTPUT
    shell: bash

  - id: initilize-repo
    uses: actions/checkout@v3
    if: ${{ !contains(steps.is-repo-initilized.outputs.remote-url, github.repository) }}

  - id: get-cargo
    uses: dtolnay/rust-toolchain@stable

  - id: install-linux
    shell: bash
    if: ${{ runner.os == 'Linux' || runner.os == 'macOS' }}
    run: |
      mkdir -p "$HOME/.local/bin"
      echo "$HOME/.local/bin" > "$GITHUB_PATH"

      curl -L 'https://github.com/kaleidawave/crates-release-gh-action/releases/download/assets/crates-release' > "$HOME/.local/bin/crates-release"
      chmod +x "$HOME/.local/bin/crates-release"

      ./$HOME/.local/bin/crates-release change-version ${{ inputs.version }}

  # if for some reason this is run on windows?
  - id: install-windows
    shell: bash
    if: ${{ runner.os == 'Windows' }}
    run: |
      mkdir "$HOME/.local/bin"
      echo "$HOME/.local/bin" > "$GITHUB_PATH"
      curl -L 'https://github.com/kaleidawave/crates-release-gh-action/releases/download/assets/crates-release.exe' > "$HOME/.local/bin/crates-release.exe"

  - id: updater
    shell: bash
    run: crates-release change-version ${{ inputs.version }}
    working-directory: ${{ inputs.working-directory }}

  - name: Publish on crates.io
    if: ${{ inputs.publish-crates == 'true' }}
    working-directory: ${{ inputs.working-directory }}
    run: cargo publish --allow-dirty --workspace
    env:
      CARGO_REGISTRY_TOKEN: ${{ inputs.crates-token }}
    shell: bash
