name: "crates-release"
description: "Increment crate version and release on crates.io"
branding:
  icon: arrow-up-circle
  color: red
author: kaleidawave

inputs:
  version:
    description: "version to release under. can be major/minor/patch or semver. defaults to patch"
    required: false
    default: "patch"
  crates-token:
    description: "crates.io token for publishing"
    required: true
  working-directory:
    description: "directory which Cargo.toml is under"
    required: false
    default: "."

outputs:
  new-version:
    description: "New version released under"
    value: ${{ steps.set-output.outputs.new-version }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        clean: false
    - name: Install cargo edit
      run: |
        echo "::group::Installing cargo edit"
        brew install cargo-edit
        echo "::endgroup::"
      shell: bash
    - name: Set version semver
      if: ${{ contains(inputs.version, '.') }}
      run: >
        echo "NEW_CRATE_VERSION=$( 
          cargo set-version ${{ inputs.version }} | awk 'NR==1 {print $NF}'  
        )" >> $GITHUB_ENV
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - name: Set version bump
      if: ${{ !contains(inputs.version, '.') }}
      run: >
        echo "NEW_CRATE_VERSION=$( 
          cargo set-version --bump ${{ inputs.version }} | awk 'NR==1 {print $NF}' 
        )" >> $GITHUB_ENV
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - name: Publish on crates.io
      run: |
        echo "::group::Cargo publish"
        cargo publish --allow-dirty
        echo "::endgroup::"
      env:
        CARGO_REGISTRY_TOKEN: ${{ inputs.crates-token }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - name: Echo release
      run: echo "Released crate under version ${{ env.NEW_CRATE_VERSION }}"
      shell: bash
    - id: set-output
      run: echo "::set-output name=new-version::${{ env.NEW_CRATE_VERSION }}"
      shell: bash
